apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-apps
  template:
    metadata:
      labels:
        app: loan-apps
    spec:
      containers:
      - name: loan-apps
        image: nginx:latest
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
