apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-apps-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-apps-production
  template:
    metadata:
      labels:
        app: payment-apps-production
    spec:
      containers:
      - name: payment-apps-production
        image: nginx:latest
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 80
