apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-apps
spec:
  selector:
    matchLabels:
      app: finance-apps
  template:
    metadata:
      labels:
        app: finance-apps
    spec:
      containers:
      - name: finance-apps
        image: rizkyperdana28/nodejs-env:latest
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
         - containerPort: 3000
        envFrom:
         - secretRef:
             name: finance-secret
