apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website-finance
spec:
  interval: 1m
  chart: 
    spec:
      chart: ./helm/application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
   image: rizkyperdana28/nodejs-env:latest
   port: 3000